use_frameworks!

target 'USStatePicker_Example' do
  pod 'USStatePicker', :path => '../'

  target 'USStatePicker_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
    pod 'Nimble', '~> 3.0'
  end
end
